<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="2" result="Failed" total="2" passed="1" failed="1" inconclusive="0" skipped="0" asserts="1" engine-version="3.9.0.0" clr-version="4.0.30319.42000" start-time="2018-11-09 00:08:15Z" end-time="2018-11-09 00:08:17Z" duration="1.592271">
  <command-line><![CDATA[nunit3-console  --where "class==Project1.TestStudent" bin\Debug\Project1.exe]]></command-line>
  <filter>
    <class>Project1.TestStudent</class>
  </filter>
  <test-suite type="Assembly" id="0-1005" name="Project1.exe" fullname="Project1.exe" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2018-11-09 00:08:16Z" end-time="2018-11-09 00:08:17Z" duration="0.711754" total="2" passed="1" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
    <environment framework-version="3.11.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.17134.0" platform="Win32NT" cwd="C:\Users\ngtro\Documents\Visual Studio 2017\Projects\Project1\Project1" machine-name="DESKTOP-VLHPCMH" user="ngtro" user-domain="DESKTOP-VLHPCMH" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Users\ngtro\Documents\Visual Studio 2017\Projects\Project1\Project1" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5" />
      <setting name="ImageRequiresX86" value="True" />
      <setting name="RunAsX86" value="True" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="17072" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1006" name="Project1" fullname="Project1" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2018-11-09 00:08:16Z" end-time="2018-11-09 00:08:17Z" duration="0.687936" total="2" passed="1" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestFixture" id="0-1000" name="TestStudent" fullname="Project1.TestStudent" classname="Project1.TestStudent" runstate="Runnable" testcasecount="2" result="Failed" site="Child" start-time="2018-11-09 00:08:16Z" end-time="2018-11-09 00:08:17Z" duration="0.684415" total="2" passed="1" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="ParameterizedMethod" id="0-1004" name="TestServer" fullname="Project1.TestStudent.TestServer" classname="Project1.TestStudent" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-11-09 00:08:16Z" end-time="2018-11-09 00:08:17Z" duration="0.668782" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1003" name="TestServer()" fullname="Project1.TestStudent.TestServer()" methodname="TestServer" classname="Project1.TestStudent" runstate="Runnable" seed="1424602704" result="Failed" label="Error" start-time="2018-11-09 00:08:16Z" end-time="2018-11-09 00:08:17Z" duration="0.662117" asserts="0">
            <failure>
              <message><![CDATA[System.AggregateException : One or more errors occurred.
  ----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
  ----> System.Net.WebException : The underlying connection was closed: The connection was closed unexpectedly.]]></message>
              <stack-trace><![CDATA[   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Project1.TestStudent.TestServer() in c:\users\ngtro\documents\visual studio 2017\Projects\Project1\Project1\TestStudent.cs:line 28
--HttpRequestException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Project1.TestStudent.<request>d__4.MoveNext() in c:\users\ngtro\documents\visual studio 2017\Projects\Project1\Project1\TestStudent.cs:line 37
--WebException
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)]]></stack-trace>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedMethod" id="0-1002" name="TestSetName" fullname="Project1.TestStudent.TestSetName" classname="Project1.TestStudent" runstate="Runnable" testcasecount="1" result="Passed" start-time="2018-11-09 00:08:17Z" end-time="2018-11-09 00:08:17Z" duration="0.009374" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="1">
          <test-case id="0-1001" name="TestSetName()" fullname="Project1.TestStudent.TestSetName()" methodname="TestSetName" classname="Project1.TestStudent" runstate="Runnable" seed="799174486" result="Passed" start-time="2018-11-09 00:08:17Z" end-time="2018-11-09 00:08:17Z" duration="0.009301" asserts="1" />
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>